 const tarotDoc = [
    {url:"img/asword.jpg", name: "Ace of Swords",upright:"Mental clarity, new ideas.",reversed:"Clouded judgement.",  },
    {url:"img/2sword.jpg", name: "Two of Swords",upright:"A decision must be made with the mind, not the heart.",reversed:"Indecision and procrastination.",  },
    {url:"img/3sword.jpg", name: "Three of Swords",upright:"Emotional pain, caused by logical decisions.",reversed:"Healing from emotional pain.",  },
    {url:"img/4sword.jpg", name: "Four of Swords",upright:"Rest and contemplation",reversed:"Exhaustion, taking a rest but feeling restless.",  },
    {url:"img/5sword.jpg", name: "Five of Swords",upright:"Winning at all costs",reversed:"Resentment.",  },
    {url:"img/6sword.jpg", name: "Six of Swords",upright:"Making sacrifices for a new start.",reversed:"Resistance to change.",  },
    {url:"img/7sword.jpg", name: "Seven of Swords",upright:"Betrayal",reversed:"Imposter Syndrome",  },
    {url:"img/8sword.jpg", name: "Eight of Swords",upright:"Fear, no actual harm done.",reversed:"Letting go of fear",  },
    {url:"img/9sword.jpg", name: "Nine of Swords",upright:"Losing sleep over fear and anxiety.",reversed:"Releasing worry.",  },
    {url:"img/10sword.jpg", name: "Ten of Swords",upright:"An abrupt end, painful loss.",reversed:"being effected by a painful loss in the past.",  },
    {url:"img/pagesword.jpg", name: "Page of Swords",upright:"Curiosity, able to communicate your ideas.",reversed:"Good ideas without action.",  },
    {url:"img/knightsword.jpg", name: "Knight of Swords",upright:"Fast-thinking action",reversed:"Restless action",  },
    {url:"img/queensword.jpg", name: "Queen of Swords",upright:"An intelligent person with advice.",reversed:"A judgemental person.",  },
    {url:"img/kingsword.jpg", name: "King of Swords",upright:"A educated leader.",reversed:"An indecisive leader.",  },

    {url:"img/apent.jpg", name: "Ace of Pentacles",upright:"New financial/career opportunities.",reversed:"Obsession with material gain.",  },
    {url:"img/2pent.jpg", name: "Two of Pentacles",upright:"Balancing financial options.",reversed:"Disorganized finances.",  },
    {url:"img/3pent.jpg", name: "Three of Pentacles",upright:"Hard work in collaboration.",reversed:"Disagreements in collaborations or at work.",  },
    {url:"img/4pent.jpg", name: "Four of Pentacles",upright:"Caution around finances.",reversed:"Lack of financial foundation.",  },
    {url:"img/5pent.jpg", name: "Five of Pentacles",upright:"Financial loss.",reversed:"Change of luck.",  },
    {url:"img/6pent.jpg", name: "Six of Pentacles",upright:"Sharing rewards, charity.",reversed:"Jealousy",  },
    {url:"img/7pent.jpg", name: "Seven of Pentacles",upright:"Reaping rewards.",reversed:"Poor return on investments.",  },
    {url:"img/8pent.jpg", name: "Eight of Pentacles",upright:"Hard work, ambition.",reversed:"lack of ambition, not living up to your potential.",  },
    {url:"img/9pent.jpg", name: "Nine of Pentacles",upright:"The \"happily single\" card, feeling secure in your own finances, independence.",reversed:"Anxiety over individual finances, possibly dependent on others.",  },
    {url:"img/10pent.jpg", name: "Ten of Pentacles",upright:"A good work/life balance, security and comfort.",reversed:"Poor work/life balance.",  },
    {url:"img/pagepent.jpg", name: "Page of Pentacles",upright:"Development of skills.",reversed:"Learning from past mistakes.",  },
    {url:"img/knightpent.jpg", name: "Knight of Pentacles",upright:"Slow but steady progress.",reversed:"Lack of self discipline.",  },
    {url:"img/queenpent.jpg", name: "Queen of Pentacles",upright:"A compassionate provider.",reversed:"An insecure person.",  },
    {url:"img/kingpent.jpg", name: "King of Pentacles",upright:"A person with good financial advice.",reversed:"A person only interested in financial gain.",  },

    {url:"img/acup.jpg", name: "Ace of Cups",upright:"New beginnings in friendships or romance.",reversed:"Insecurity about romantic or platonic connections.",  },
    {url:"img/2cup.jpg", name: "Two of Cups",upright:"A new partnership, mutual respect and loyalty.",reversed:"End of a partnership, or misaligned loyalty",  },
    {url:"img/3cup.jpg", name: "Three of Cups",upright:"Group outings and new friend groups.",reversed:"Excess, overindulgence.",  },
    {url:"img/4cup.jpg", name: "Four of Cups",upright:"Taking a step back from society, isolation",reversed:"Coming back into society, starting new relationships.",  },
    {url:"img/5cup.jpg", name: "Five of Cups",upright:"Emotional loss, confronting ones own grief.",reversed:"Moving on from grief.",  },
    {url:"img/6cup.jpg", name: "Six of Cups",upright:"Nostalgia, something from your pasrt returns.",reversed:"Time to leave unpleasant memories behind.",  },
    {url:"img/7cup.jpg", name: "Seven of Cups",upright:"Unable to make a decision, not all options are feasible.",reversed:"Making a pragmatic decision.",  },
    {url:"img/8cup.jpg", name: "Eight of Cups",upright:"Finally letting go of a toxic situation.",reversed:"Trying to make something work one last time.",  },
    {url:"img/9cup.jpg", name: "Nine of Cups",upright:"The \"wish\" card! Success.",reversed:"Dissatisfaction, \"Be careful what you wish for\".",  },
    {url:"img/10cup.jpg", name: "Ten of Cups",upright:"Happy ending, satisfying home life",reversed:"Troubles at home.",  },
    {url:"img/pagecup.jpg", name: "Page of Cups",upright:"Communication of feelings, being understood.",reversed:"Unable to communicate emotions, feeling misunderstood.",  },
    {url:"img/knightcup.jpg", name: "Knight of Cups",upright:"Acting with emotional intelligence and charm.",reversed:"Acting with low emotional intelligence and jealousy.",  },
    {url:"img/queencup.jpg", name: "Queen of Cups",upright:"A nurturing, compassionate person.",reversed:"A co-dependent person.",  },
    {url:"img/kingcup.jpg", name: "King of Cups",upright:"A diplomatic person.",reversed:"An emotionally manipulative person",  },

    {url:"img/awand.jpg", name: "Ace of Wands",upright:"New opportunities or inspiration.",reversed:"Lots of energy, but lack of direction/outlet.",  },
    {url:"img/2wand.jpg", name: "Two of Wands",upright:"Patience, long term planning.",reversed:"Short sighted, may need a new plan for the same goal.",  },
    {url:"img/3wand.jpg", name: "Three of Wands",upright:"Progress, leaving your comfort zone.",reversed:"\"Playing small\", expansion may be necessary.",  },
    {url:"img/4wand.jpg", name: "Four of Wands",upright:"Celebration, appreciation for what you have, the \"Marriage\" card.",reversed:"Lack of appreciation for what you already have, or the people in your life.",  },
    {url:"img/5wand.jpg", name: "Five of Wands",upright:"Conflict and confusion, think before you act.",reversed:"Litigation and disputes, making the best out of a bad situation",  },
    {url:"img/6wand.jpg", name: "Six of Wands",upright:"Recognition and success after struggling, possible travel.",reversed:"Self confidence without recognition",  },
    {url:"img/7wand.jpg", name: "Seven of Wands",upright:"Perseverence, being challenged.",reversed:"Exhaustion, ready to give up.",  },
    {url:"img/8wand.jpg", name: "Eight of Wands",upright:"Freedom of movement, faster pace.",reversed:"Resistance to change, delays.",  },
    {url:"img/9wand.jpg", name: "Nine of Wands",upright:"Resilience, willing to defend yourself.",reversed:"Paranoia, overwhelmed by criticism.",  },
    {url:"img/10wand.jpg", name: "Ten of Wands",upright:"Carrying too many burdens, weighed down.",reversed:"Letting go of burdens, no longer weighed down",  },
    {url:"img/pagewand.jpg", name: "Page of Wands",upright:"Creative communication, inspiration, possible collaboration.",reversed:"Lots of ideas, but unable to communicate them effectively.",  },
    {url:"img/knightwand.jpg", name: "Knight of Wands",upright:"Fast paced pursuit of a goal",reversed:"Impulsivity, lack of inspiration.",  },
    {url:"img/queenwand.jpg", name: "Queen of Wands",upright:"Confidence and ambition, an independent person.",reversed:"Self respect, outward aggression.",  },
    {url:"img/kingwand.jpg", name: "King of Wands",upright:"Encouraging and optimistic, a person with advice",reversed:"Pessimism, an insecure person.",  },


]


export default tarotDoc